/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HashGraphRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "attestBatch"
      | "authorizeAttester"
      | "authorizedAttesters"
      | "getAllProtocols"
      | "getAttestation"
      | "isVerified"
      | "owner"
      | "revoke"
      | "totalProtocols"
      | "transferOwnership"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttesterAuthorized"
      | "AttesterRevoked"
      | "GraphAttested"
      | "GraphRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "attestBatch",
    values: [AddressLike[], BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAttesters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProtocols",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "revoke", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalProtocols",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAttesters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace AttesterAuthorizedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterRevokedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GraphAttestedEvent {
  export type InputTuple = [
    protocol: AddressLike,
    graphHash: BytesLike,
    attester: AddressLike,
    metadataURI: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    protocol: string,
    graphHash: string,
    attester: string,
    metadataURI: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    protocol: string;
    graphHash: string;
    attester: string;
    metadataURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GraphRevokedEvent {
  export type InputTuple = [
    protocol: AddressLike,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    protocol: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    protocol: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HashGraphRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HashGraphRegistry;
  waitForDeployment(): Promise<this>;

  interface: HashGraphRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [protocol: AddressLike, graphHash: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  attestBatch: TypedContractMethod<
    [
      protocols: AddressLike[],
      graphHashes: BytesLike[],
      metadataURIs: string[]
    ],
    [void],
    "nonpayable"
  >;

  authorizeAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedAttesters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAllProtocols: TypedContractMethod<[], [string[]], "view">;

  getAttestation: TypedContractMethod<
    [protocol: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        graphHash: string;
        metadataURI: string;
        attester: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  isVerified: TypedContractMethod<[protocol: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  revoke: TypedContractMethod<[protocol: AddressLike], [void], "nonpayable">;

  totalProtocols: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [protocol: AddressLike, graphHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [protocol: AddressLike, graphHash: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestBatch"
  ): TypedContractMethod<
    [
      protocols: AddressLike[],
      graphHashes: BytesLike[],
      metadataURIs: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedAttesters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllProtocols"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [protocol: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        graphHash: string;
        metadataURI: string;
        attester: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[protocol: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[protocol: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalProtocols"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [protocol: AddressLike, graphHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AttesterAuthorized"
  ): TypedContractEvent<
    AttesterAuthorizedEvent.InputTuple,
    AttesterAuthorizedEvent.OutputTuple,
    AttesterAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterRevoked"
  ): TypedContractEvent<
    AttesterRevokedEvent.InputTuple,
    AttesterRevokedEvent.OutputTuple,
    AttesterRevokedEvent.OutputObject
  >;
  getEvent(
    key: "GraphAttested"
  ): TypedContractEvent<
    GraphAttestedEvent.InputTuple,
    GraphAttestedEvent.OutputTuple,
    GraphAttestedEvent.OutputObject
  >;
  getEvent(
    key: "GraphRevoked"
  ): TypedContractEvent<
    GraphRevokedEvent.InputTuple,
    GraphRevokedEvent.OutputTuple,
    GraphRevokedEvent.OutputObject
  >;

  filters: {
    "AttesterAuthorized(address)": TypedContractEvent<
      AttesterAuthorizedEvent.InputTuple,
      AttesterAuthorizedEvent.OutputTuple,
      AttesterAuthorizedEvent.OutputObject
    >;
    AttesterAuthorized: TypedContractEvent<
      AttesterAuthorizedEvent.InputTuple,
      AttesterAuthorizedEvent.OutputTuple,
      AttesterAuthorizedEvent.OutputObject
    >;

    "AttesterRevoked(address)": TypedContractEvent<
      AttesterRevokedEvent.InputTuple,
      AttesterRevokedEvent.OutputTuple,
      AttesterRevokedEvent.OutputObject
    >;
    AttesterRevoked: TypedContractEvent<
      AttesterRevokedEvent.InputTuple,
      AttesterRevokedEvent.OutputTuple,
      AttesterRevokedEvent.OutputObject
    >;

    "GraphAttested(address,bytes32,address,string,uint256)": TypedContractEvent<
      GraphAttestedEvent.InputTuple,
      GraphAttestedEvent.OutputTuple,
      GraphAttestedEvent.OutputObject
    >;
    GraphAttested: TypedContractEvent<
      GraphAttestedEvent.InputTuple,
      GraphAttestedEvent.OutputTuple,
      GraphAttestedEvent.OutputObject
    >;

    "GraphRevoked(address,address,uint256)": TypedContractEvent<
      GraphRevokedEvent.InputTuple,
      GraphRevokedEvent.OutputTuple,
      GraphRevokedEvent.OutputObject
    >;
    GraphRevoked: TypedContractEvent<
      GraphRevokedEvent.InputTuple,
      GraphRevokedEvent.OutputTuple,
      GraphRevokedEvent.OutputObject
    >;
  };
}
